# Generated by Django 4.0.1 on 2022-01-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BookID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Author', models.CharField(max_length=100)),
                ('ISBN', models.CharField(max_length=13)),
                ('Edition', models.IntegerField()),
                ('OriginalPrice', models.FloatField()),
                ('AveragePrice', models.FloatField()),
            ],
        ),
    ]
