# Generated by Django 4.0.1 on 2022-01-15 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCode',
            fields=[
                ('ClassName', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Faculty', models.CharField(max_length=255)),
                ('Department', models.CharField(max_length=100)),
                ('BookID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Books.book')),
            ],
        ),
    ]
