# Generated by Django 4.0.1 on 2022-01-15 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookListing',
            fields=[
                ('ListingID', models.BigAutoField(primary_key=True, serialize=False)),
                ('ListPrice', models.FloatField()),
                ('DateAdded', models.DateTimeField()),
                ('Sold', models.BooleanField()),
                ('BookImage', models.ImageField(upload_to='')),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.book')),
            ],
        ),
    ]
