# Generated by Django 4.0.1 on 2022-01-16 02:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BookListings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklisting',
            name='BookImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='booklisting',
            name='DateAdded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
