# Generated by Django 4.0.1 on 2022-01-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_classes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='previous_classes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
